mcoauth/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('mcoauth.core.urls')),
    url(r'^accounts/', include('mcoauth.accounts.urls')),
    url(r'^apps/', include('mcoauth.apps.urls', namespace='app')),
    #url(r'^minecraft/', include('mcoauth.mcaccounts.urls',
    #    namespace='minecraft')),
    url(r'^oauth/', include('mcoauth.oauth.urls', namespace='oauth2')),
    url(r'^api/', include('mcoauth.api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mineid/apps/urls.py
from django.conf.urls import patterns, include, url

from .views import AppList, AppCreate, AppUpdate, AppDelete, AppCredentials

urlpatterns = patterns(
    '',
    url(r'^$', AppList.as_view(), name='list'),
    url(r'^create/$', AppCreate.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', AppUpdate.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', AppDelete.as_view(), name='delete'),
    url(r'^credentials/(?P<pk>\d+)/$', AppCredentials.as_view(),
        name='credentials'),
)

mineid/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('mineid.core.urls')),
    url(r'^accounts/', include('mineid.accounts.urls')),
    url(r'^apps/', include('mineid.apps.urls', namespace='app')),
    #url(r'^minecraft/', include('mineid.mcaccounts.urls',
    #    namespace='minecraft')),
    url(r'^oauth/', include('mineid.oauth.urls', namespace='oauth2')),
    url(r'^api/', include('mineid.api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% extends 'bootstrap.html' %}

{% load i18n %}
{% load static %}
{% load bootstrap3 %}

{% block bootstrap3_content %}
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">{% trans "Toggle navigation" %}</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url "home" %}#page-top">MineID.org</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="{% url "home" %}#page-top"></a>
                    </li>
                    {% block menu %}
                        {% if request.user.is_authenticated %}
                            <li>
                                <a href="{% url "app:list" %}">{% trans "Applications" %}</a>
                            </li>
                            <li>
                                <a href="{% url "password_change" %}">{% trans "Change password" %}</a>
                            </li>
                            <li>
                                <a href="{% url "auth_logout" %}">{% trans "Sign out" %}</a>
                            </li>
                        {% else %}
                            <li class="page-scroll">
                                <a href="{% url "home" %}#about">{% trans "about" %}</a>
                            </li>
                            <li class="page-scroll">
                                <a href="{% url "home" %}#contact">{% trans "how it works" %}</a>
                            </li>
                            <li>
                                <a href="{% url "auth_login" %}">{% trans "sign in" %}</a>
                            </li>
                        {% endif %}
                    {% endblock %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    {% bootstrap_messages %}

    {% block content_wrapper %}
        <section id="content">
            <div class="container">
                <div class="row">
                    {% block content %}
                        {% block content_title %}
                            <h1 class="page-header">{% block title %}{% endblock %}</h1>
                        {% endblock %}
                    {% endblock %}
                </div>
            </div>
        </section>
    {% endblock %}

    <!-- Footer -->
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        <h3>{% trans "Created in partnership with" %}</h3>
                        <ul class="list-unstyled">
                            <li>
                                <h4><a href="http://www.playgrid.com">PlayGrid</a></h4>
                            </li>
                            <li>
                                <h4><a href="http://www.getnodecraft.com">Nodecraft</a></h4>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>{% trans "Review the code and contribute!" %}</h3>
                        <ul class="list-inline">
                            <li>
                                <a href="http://github.com/MineID/MineID" class="btn-social btn-outline"><i class="fa fa-fw fa-github"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-top page-scroll visible-xs visble-sm">
        <a class="btn btn-primary" href="#page-top">
            <i class="fa fa-chevron-up"></i>
        </a>
    </div>
{% endblock %}

templates/base_form.html
{% extends 'base.html' %}

{% load i18n %}
{% load bootstrap3 %}

{% block content %}
    {{ block.super }}
    {% bootstrap_form_errors form %}
    <form method="POST" action="{{ request.path }}{% if next %}?next={{ next|urlencode }}{% endif %}">
        {% csrf_token %}
        {% block form %}
            {% bootstrap_form form %}
        {% endblock %}
        {% block form_buttons %}
            {% buttons submit=form_submit|default:_('Save') %}
                {% if cancel_url %}
                    {% trans "or" %}
                    <a href="{{ cancel_url }}">{{ form_cancel|default:_('Cancel') }}</a>
                {% endif %}
            {% endbuttons %}
        {% endblock %}
    </form>
{% endblock %}

templates/bootstrap.html
<!DOCTYPE html>
{% load bootstrap3 static %}
<html{% if request.LANGUAGE_CODE %} lang="{{ request.LANGUAGE_CODE }}"{% endif %}>

<head>
    <meta charset="utf-8">
    <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge" /><![endif]-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}</title>
    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    <!-- MineID -->
    <link href="{% static "css/mineid.css" %}" rel="stylesheet" type="text/css">
    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% if 'javascript_in_head'|bootstrap_setting %}{% bootstrap_javascript jquery=True %}{% endif %}
    {% block bootstrap3_extra_head %}{% endblock %}
</head>

<body{% block body_attrs %}{% endblock %}>
{% block bootstrap3_content %}{% endblock %}
<!-- jQuery -->
<script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
<!-- Bootstrap -->
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<!-- Plugin JavaScript -->
<script src="{% static "js/jquery.easing.min.js" %}"></script>
<script src="{% static "js/classie.js" %}"></script>
<script src="{% static "js/cbpAnimatedHeader.js" %}"></script>
<!-- MineID -->
<script type="text/javascript" src="{% static "js/mineid.js" %}"></script>
{% block bootstrap3_extra_script %}{% endblock %}
</body>

</html>