mcoauth/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('mcoauth.core.urls')),
    url(r'^accounts/', include('mcoauth.accounts.urls')),
    url(r'^apps/', include('mcoauth.apps.urls', namespace='app')),
    #url(r'^minecraft/', include('mcoauth.mcaccounts.urls',
    #    namespace='minecraft')),
    url(r'^oauth/', include('mcoauth.oauth.urls', namespace='oauth2')),
    url(r'^api/', include('mcoauth.api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mineid/oauth/urls.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from provider.compat.urls import *
from provider.oauth2.views import Redirect, Capture, AccessTokenView
from .views import Authorize


urlpatterns = patterns('',
    url('^authorize/?$',
        login_required(Capture.as_view()),
        name='capture'),
    url('^authorize/confirm/?$',
        login_required(Authorize.as_view()),
        name='authorize'),
    url('^redirect/?$',
        login_required(Redirect.as_view()),
        name='redirect'),
    url('^access_token/?$',
        csrf_exempt(AccessTokenView.as_view()),
        name='access_token'),
)

mineid/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('mineid.core.urls')),
    url(r'^accounts/', include('mineid.accounts.urls')),
    url(r'^apps/', include('mineid.apps.urls', namespace='app')),
    #url(r'^minecraft/', include('mineid.mcaccounts.urls',
    #    namespace='minecraft')),
    url(r'^oauth/', include('mineid.oauth.urls', namespace='oauth2')),
    url(r'^api/', include('mineid.api.urls', namespace='api')),
    url(r'^admin/', include(admin.site.urls)),
)


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/provider/authorize.html
{% extends 'base.html' %}

{% load i18n %}
{% load scope %}
{% load bootstrap3 %}
{% load static %}

{% block menu %}{% endblock %}

{% block bootstrap3_extra_head %}
    <link href="{% static "css/authorize.css" %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
    <h1 class="page-header">{% if error %}{% trans "Confirm Authorization" %}{% endif %}</h1>
    <div class="jumbotron">
        {% if not error %}
            <h2>{{ client.name }}</h2>
            <p class="desc">{% trans "would like to access your data with the following permissions:" %}</p>
            <ul class="list-group">
                {% for permission in oauth_data.scope|scopes %}
                    <li class="list-group-item" style="text-align:left">
                        {% if permission == "retrieve_accounts" %}
                        {% bootstrap_icon "download" %} {% trans "Retrieve email address, player name, and player unique id for your Minecraft accounts" %}
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
            <form method="post" action="{% url "oauth2:authorize" %}">
                {% csrf_token %}
                {% bootstrap_form_errors form %}
                <fieldset>
                    <div style="display: none;" />
                        <select type="select" name="scope" multiple="multiple">
                        {% for scope in oauth_data.scope|scopes %}
                            <option value="{{ scope }}" selected="selected">{{ scope }}</option>
                        {% endfor %}
                        </select>
                    </div>
                    {% url "switch_account" as switch_account_url %}
                    {% with switch_account_url=switch_account_url|add:"?next="|add:request.path %}
                        <p class="desc"><small>{% blocktrans with user=request.user.email %}You're logged in as {{ user }}, <a href="{{ switch_account_url }}">click here to switch</a>.{% endblocktrans %}</small></p>
                    {% endwith %}
                    <div class="desc">
                        <input type="submit" class="btn" value="{% trans "Cancel" %}" />
                        <input type="submit" class="btn btn-success" name="authorize" value="{% trans "Authorize" %}" />
                    </div>
                </fieldset>
            </form>
        {% else %}
            {{ error }}
            {{ error_description }}
        {% endif %}
    </div>
{% endblock %}